### ISSUE TITLE
Move documentation to Sphinx

### ISSUE THREAD

**Issue by ashnwade** [gravwell/wiki#535]
## Overview
Sphinx is a very useful documentation generator. It will offer better searching capabilities and looks good on mobile.

### Implementation
- [x] add toctrees to existing documents
- [x] add admonitions (e.g. Note, Attention, Warning)
- [x] merge in latest changes from dev (repeat first two steps for new additions)
- [X] cache busting (maybe useful: https://httpd.apache.org/docs/2.2/mod/core.html#FileETag)
- [X] Redirects for existing links
- [x] Customize not found page (logbot?)
- [x] Configure web server to use new HTML page

### After Release
- [x] https://github.com/gravwell/backend-issues/issues/4931
- [x] https://github.com/gravwell/frontend-issues/issues/5825
- [x] #549

### Other enhancements
- [x] Include abbreviated commit hash in footer

**Comment by kris-watts-gravwell** [comment]
we can't do `https://staging.docs.gravwell.io/#!search/chart/chart.md` -> `https://staging.docs.gravwell.io/search/chart/chart.html` server side because the server never sees anything in the URL past the `#`.

the new index.html will need a javascript snippet to see those URLs and do a redirect within the client.

**Comment by kris-watts-gravwell** [comment]
staging is throwing ETag now.  works.
