### ISSUE TITLE
maintain history of docs and navigation menu to get to older versions

### ISSUE THREAD

**Issue by kris-watts-gravwell** [gravwell/wiki#838]
## Who was the customer who requested this feature?

Several

## What is the feature to be added?

The product moves pretty quickly, so new stuff is coming all the time.  We need to make sure to call out enhancements directly in documentation with version numbers.

For example, when a new module is introduced users may not know that their current version doesn't have it.  We need to make it easy for users to navigate does for THEIR version.

## Why should we add this feature? (Business justification? What problem is the feature trying to solve?)

Not all users are at the latest version, in fact rarely so.  So when something is asked for they may not know when it was introduced or they attempt to use new functionality in old versions.

This will ensure that when they go through docs they know that they can't use something unless they upgrade to X.Y.Z.

## How does this feature address the above problem?

Makes it obvious when we document something what version is required to use it.

## Tasks

- [x] Enable [version switcher](https://pydata-sphinx-theme.readthedocs.io/en/stable/user_guide/version-dropdown.html)
- [x] Decide path layout
      - `/` Latest (keeps previously-published links working)
      - `/vN.N.N/` Previous releases
- [x] Add `robots.txt` to prevent search engines from indexing `/vN.N.N` paths?

**Comment by michael-wisely-gravwell** [comment]
Angular's Doc Versions are pretty nice too

Pros:
- Easy to select a version
- Subdomain indicates the version

Cons:
- Version for `stable` is implied - I'd prefer to see  v17 in there
- `stable` doesn't use a subdomain or version in URL, so it's harder to permalink
- Unless the Documentation Version collapsible is open, it's not obvious what version I'm looking at


<img width="382" alt="image" src="https://github.com/gravwell/wiki/assets/108433848/5a00940e-ae5f-42fd-bdea-b1ca4525a6f6">

**Comment by michael-wisely-gravwell** [comment]
The Pydata sphinx theme (which we use) does a great job with version

Pros:
- It's in the navbar, always visible through scroll
- It's a dropdown, easy to figure out
- Version's in the URL

Cons:
- Color highlights `stable`, not "currently selected", which feels a little odd to me

<img width="689" alt="image" src="https://github.com/gravwell/wiki/assets/108433848/edfe9af7-f0b6-493a-b775-a9d8ac446e54">

**Comment by ashnwade** [comment]
When stable is the version selected, there is a very obvious color highlight on whichever version you are hovering on. When you are on an older version, it does the color highlight on the stable version (as Wisely described). In that view (where an older version is selected), the background color of the cell does change for whichever version you are hovering on, but it is _very_ subtle on the dark theme; the light theme it is much easier to see. May not need to change the behavior if we can customize the color scheme to make it a little more obvious?

**Comment by kris-watts-gravwell** [comment]
so we just need a robots.txt file that is automatically created using the list of tails that basically contains the following:
```
Disallow: /v5.4.6/*
Disallow: /v5.4.7/*
Disallow: /v5.4.8/*
```
